### ISSUE TITLE
Consider adding a non-Twitter social media presence

### ISSUE THREAD

**Issue by voxpelli** [opensourcepledge/opensourcepledge.com#195]
With more and more people reluctant to have a presence on Twitter due to eg. Elon Musks interactions, endorsements and changes – and with eg. Threads becoming more and more interoperable with the Fediverse, adding either a Threads account or a Mastodon account would enable many more people to follow the initiative and make it less reliant on what in some circles is becoming a controversial platform.

Threads would enable both Threads users and Fediverse users to follow, so that would be the easiest one I think.

**Comment by vladh** [comment]
Sounds good to me. I would go for Mastodon over Threads, because this gives us a presence that is maximally insulated from any social media company's actions/reputation.

**Comment by chadwhitacre** [comment]
Who is volunteering to run these? :)

**Comment by voxpelli** [comment]
One option is to use it only for posting and not so much for reading, then making it post through PR:s using eg https://github.com/humanwhocodes/toot#using-in-a-github-workflow can make sense

The nicer option would be to use something like Buffer to join all the interactions into one tool that a couple of people can collaborate on

**Comment by Delta456** [comment]
> Who is volunteering to run these? :)

I can volunteer for running the LinkedIn page if everyone agrees.

**Comment by vladh** [comment]
I think we need to consider #197 first, so that we (1) have a consistent brand voice, even if it's just made up of super minimal guidelines, and that we (2) decide on one or two people who are responsible for outward communication, to avoid each social media account having a different voice and things getting confusing.

I think it's better to have fewer accounts that are properly managed, than give ourselves too much work. So let's think about what's really necessary. 🤔

**Comment by andypiper** [comment]
fosstodon.org may be a good fit?
