### ISSUE TITLE
Add individual membership

### ISSUE THREAD

**Issue by mishushakov** [opensourcepledge/opensourcepledge.com#21]
I spoke with Kyle from GitHub and with David (Sentry) about this quite a bit and would love to join as an individual fund.

I'm already sponsoring some folks through GitHub Sponsors, but I feel what would be awesome is to also highlight how individuals can take part in Open Source Pledge.

**Comment by vladh** [comment]
Amazing, thank you! I think this is fine since we already have members who only have one developer.

The only question that I can think of is how/if companies and individuals should be differentiated (1) in the marketing materials and (2) on the website. Perhaps the best way to solve this cleanly is to say that we don't make a differentiation, but we just sort members by pledge amount, which I hope will incentivise further high-pledge members.

@chadwhitacre what do you think?

**Comment by mishushakov** [comment]
Open Collective for instance makes that distinction: https://opencollective.com/curl

**Comment by chadwhitacre** [comment]
Relevant: https://ziglang.org/news/300k-from-mitchellh/

**Comment by vinogradovkonst** [comment]
Individual membership would be a great addition, especially if combined with some special tiers in the future. One of good examples is https://wikimediaendowment.org/#benefactors. I would be more than pleased to join as an individual!

**Comment by voxpelli** [comment]
Since the purpose of the Open Source Pledge is to `Pay your share` I think the focus should be kept to companies.

Non-businesses have no "share" to pay and while their donations are admirable, they are not the focus of the Open Source Pledge I think and would if anything distract from the purpose and risk enforcing that OSS-donations are primarily something that non-businesses do, and that's the very thing the Open Source Pledge tries to combat?

---

If one were to pursue this though, then it should be considered whether encouraging private donations generally is advisable, see eg: https://dev.to/voxpelli/open-source-and-taxes-a-swedish-perspective-gkn

Donations from money that's been taxed as salary is generally not advisable I think – from private foundations or wealth accrued through non-salary means can make sense, but that's more similar to a company donation than an individual donation.

**Comment by sandstrom** [comment]
> Since the purpose of the Open Source Pledge is to Pay your share I think the focus should be kept to companies.
> 
> Non-businesses have no "share" to pay and while their donations are admirable, they are not the focus of the Open Source Pledge I think and would if anything distract from the purpose and risk enforcing that OSS-donations are primarily something that non-businesses do, and that's the very thing the Open Source Pledge tries to combat?

I agree with this.

I don't think there will be a lot of money in individuals contributing either, and it's not like there is anything stopping anyone from contributing.

The focus of this pledge should be companies.

Also, there is some administrative overhead here too -- another reason for this project to focus on getting companies to donate.

**Comment by vinogradovkonst** [comment]
> Since the purpose of the Open Source Pledge is to `Pay your share` I think the focus should be kept to companies.
> 
> Non-businesses have no "share" to pay and while their donations are admirable, they are not the focus of the Open Source Pledge I think and would if anything distract from the purpose and risk enforcing that OSS-donations are primarily something that non-businesses do, and that's the very thing the Open Source Pledge tries to combat?

Every person consuming modern software-enabled goods and services indirectly relies on open source as a public good. So, one always has a "share" to pay from a goodwill perspective. Individuals should be encouraged to donate together with companies, and several general-purpose pledges are doing this, for instance, [founderspledge.com](http://founderspledge.com/) and [givingpledge.org](http://givingpledge.org/).

The issue is that because >95% of software uses OSS, in most cases, organizations behind OSS-enabled products are not tech-savvy and are unlikely to ever join the Open Source Pledge, unfortunately. They are airports, hospitals, retailers, energy providers, governments (Germany is an exception here), etc.

If the ultimate goal of the Pledge is to "**pay maintainers**" to enable sustainable OSS maintenance, it should probably accept everybody who can contribute to this cause.

**Comment by voxpelli** [comment]
> Every person consuming modern software-enabled goods and services indirectly relies on open source as a public good.  So, one always has a "share" to pay from a goodwill perspective.

It's much harder for the individual to `Pay a share` of that goodwill than it is for a company to `Pay a share` of the profit they are making on their OSS use.

A company that `Pays their share` are "investing" (see #173) in the OSS projects they profit from and will gain dividends on that investment by being able to continue to profit from that OSS.

An individual sharing goodwill or doing donations to a project they are not making any financial gains on, that's charity and puts the OSS projects in competition with other charitable causes rather than in competition with proprietary software projects.

> If the ultimate goal of the Pledge is to "pay maintainers" to enable sustainable OSS maintenance, it should probably accept everybody who can contribute to this cause.

I think the goal of the Open Source Pledge is for those profiting from OSS to share that profit with OSS.

Individuals support OSS as they support any charity and that is a danger – because when OSS is seen as charity that means that sponsorships are donations, not an investments.

Companies should see OSS sponsorships as investments (see #173). Including individual charitable donations in the Open Source Pledge would be at odds with that.

**Comment by voxpelli** [comment]
> For example, I might use a library in a personal project, and see that it's not as well-maintained as I would like, so I pay to support the maintainer, so they have more time to work on it, which means the library my personal project relies on will be better, which benefits my personal project. That's a kind of investment.

If you invest in renovating your house or car you can sell the house or car for a better price later on. Sometimes the investment will even cause the valuation to increase more than the cost of the renovation, making it a no-brainer and easy to finance with eg. loans.

If you "invest" in spending time with your kids or exploring the world or supporting a creator that you love – then you will gain joy and happiness in life, but you won't be able to sell it and convert it into money later.

> Some individuals do also make an income from software they wrote that uses Open Source packages. Basically — what's the difference between an individual and a company-of-one?

This is where it gets blurry and where it comes down to definitions and different jurisdictions.

In Swedish jurisdiction you will need to register a company if you gain the income through an activity that you do for profit. If you don't do it for the profit, then you may get away with declaring the income as a "hobby" income without registering a company – especially if you do it in your spare time and its not your main income. The taxes will be the same, but the legal demands on accounting etc is different.

All in all I would say:

If you do it for profit or if its your main income then its a company-of-one no matter if you have registered it or not.

>  And more generally, I don't know how the direct-financial-gain line squares with our general incentives for the Pledge, a lot of which have to do with things like **preventing security issues, including in global supply chains**, for a generally healthy ecosystem. That's not an investment for direct financial gain. But it's still an investment.

One could argue that supporting organizations like EFF, Reporters Without Borders, Greenpeace, Amnesty International also helps preventing security issues. Not an investment for direct financial gain. But it's still an investment?

If eg. a government starts outlawing encryption, then that's quite the supply chain security issue, and if data centers are at risk of disruption due to global warming or by [internet connections being cut](https://www.bbc.com/news/articles/c748210k82wo) in the sea then that's quite a severe Denial of Service threat.

So if the direct financial gain is not a factor, then one could argue that narrowing it to just OSS projects and that maybe some other organizations should also be included, eg. EFF at least?

(One additional note when it comes to jurisdictions: Some direct financial gain is probably needed in many jurisdictions for the support to be deductible and not seen as charity. I have written [about the asymmetric nature that causes in OSS donations and taxes](https://dev.to/voxpelli/open-source-and-taxes-a-swedish-perspective-gkn) in eg. Sweden. $2000 pre-tax or post-tax has quite a different cost for a company. If companies can't deduct their support from their profits, then its much harder to motivate the support + the money will likely be double taxed as the receiver will be paying income tax as well, so the only winner is the government as they will earn the most)

**Comment by vladh** [comment]
OK! That's helpful, thank you — I think we're moving towards something clearer here.

> If you do it for profit or if its your main income then its a company-of-one no matter if you have registered it or not.

So by this definition, a sole proprietorship — or to be more specific to what you're saying, an _enskild firma_ ([en][ef-en], [se][ef-se]) — would be allowed to join? (I guess it is a _firma_ after all 😛)

[ef-en]: https://verksamt.se/en/setting-up/choose-business-type/sole-trader
[ef-se]: https://verksamt.se/starta-foretag/valj-foretagsform/enskild-naringsverksamhet

**Comment by voxpelli** [comment]
> So by this definition, a sole proprietorship — or to be more specific to what you're saying, an enskild firma ([en](https://verksamt.se/en/setting-up/choose-business-type/sole-trader), [se](https://verksamt.se/starta-foretag/valj-foretagsform/enskild-naringsverksamhet)) — would be allowed to join?

Totally! And that’s what I’m registered as, but for me currently it’s a catch 22 where I would need more OSS income to participate 😂

**Comment by vladh** [comment]
Okay! That works for me. We can say that members have to be commercial entities, regardless of what kind. This also gives us some financial/accounting predictability down the line.

**Comment by vinogradovkonst** [comment]
As a professional investor, I don't think that "invest" is the right word for most OSS funding cases. [By definition](https://dictionary.cambridge.org/dictionary/english/investment), investment is "the act of putting money, effort, time, etc. into something to make a profit or get an advantage." In other words, private benefits.

One can obviously turn private resources into private "benefits" — not only by buying shares in startups, but also by renovating one's own house or spending time with their own kids, as mentioned above. Profits or joy in such cases are private outcomes. But OSS is a public good. 

There are cases when a company puts its own resources into public goods because it plans to get an advantage. Thus, for instance, Meta invests in Llama development, and open-core startups invest in their OSS. There is a great old [essay](https://www.joelonsoftware.com/2002/06/12/strategy-letter-v/) on this topic. However, it is a pure business strategy, and companies do not need any extra encouragement to do this. It's a fiduciary duty of their managers.

But in most cases, one can't make a profit or get an advantage from putting their own resources into a public good. Otherwise, there would be no tragedy of the commons and no need for any OSS pledges. But because OSS is a public good (non-excludable and non-rivalrous), there is almost no way to get an advantage against other market players.

Thus, it is not an investment for most funders. If they still do this, they use private resources for the public benefit — that's philanthropy (btw, like in other well-known pledges). The same applies to supporting creators (without getting anything back) or donating to Greenpeace or Amnesty International.

**Comment by chadwhitacre** [comment]
> So, it is not an investment for most funders. If they still do this, they use private resources for the public benefit — that's charity (btw, like in other well-known pledges).

I agree that investment is not the right word. For me at Sentry it's not charity, though, because I'm paying not for a public good in the abstract but for value directly received. I'm reciprocating for a gift.

**Comment by chadwhitacre** [comment]
Hah, sorry, thought we were on #173. :o)

**Comment by vladh** [comment]
I've been thinking about all of the arguments presented here — thank you everyone, by the way — and I think we should allow individual membership. I've set out my arguments, and counterarguments, in #290.

**Comment by coni2k** [comment]
If I'm not late to the party, here are my two cents:

Our goal is to address the problem of not capturing the value that open ecosystems create in the economy:
- ​​Open Source Initiative A creates a software solution.
- Enterprise B consumes this solution and gains some utility (reduced cost, improved quality of service, or similar).
- Enterprise B enters into a commercial transaction with Consumer C and profits from it.

At the moment of the transaction, Enterprise B has materialized the value it has gained from the open source solution.

We expect Enterprise B to return some of this gained value to Open Source Initiative A, thereby "closing the transaction." That will make A financially sustainable and allow it to continue to produce more value for B and others.

Although both parties will benefit from the outcome in the long run, somehow, we fail to close this transaction.

***

Based on this example, it should be clear that we cannot add any condition for returning the money. A has already completed its part of the transaction (produced a software solution) and B has already consumed it. The only action left is for B to return A's fair share.

So, the correct terminology should be "payment" or, from A's perspective, "income" (not an investment, donation, or grant).

Chad Whitacre has mentioned this detail many times in his writings ~ no hoops (I would replace "person" with a "software company", but that's more of a semantic detail):
> "Open Source sustainability is when any smart, motivated person can produce widely adopted Open Source software and get paid fairly without jumping through hoops."
https://openpath.quest/2024/the-open-source-sustainability-crisis/

***

As for the solution, the Open Source Pledge is trying to achieve this result by using social pressure and/or the marketing value of the process. It's a wonderful experiment, and I hope it succeeds.

But as Konstantin points out, and as we're starting to accept widely, open source software is a public good.

From Investopedia:
> "A public good is a commodity or service that every member of a society can use without reducing its availability to all others. Typically, a public good is provided by a government and funded through taxes."
https://www.investopedia.com/terms/p/public-good.asp

The main difference with open source software is that this time, the public good is provided by the private sector instead of the government. This is a huge economic development because when it comes to production, the private sector will produce much more efficient results than the government due to the competition factor.

On the other hand, collecting taxes is still the only reliable way to finance public goods, or in other words, to split the "open source bill" among all the beneficiaries (there is also the advertising model, but let me ignore that for now).

I won't go into more detail as the text is getting too long. The solution could be something like this, with a dedicated tax for open source. As a start:
- Introduce a 1% #OpenSourceTax on every sale of proprietary software (in practice, increase the value-added tax by 1%).
- Pool the money under national public funds like the Sovereign Tech Agency.
- Distribute the money back to the open source ecosystem regularly using algorithms (based on usage and importance metrics), as [many](https://kvinogradov.com/algo-sponsors/) [of](https://funds.ecosyste.ms/) [us](https://dev.to/coni2k/open-source-public-fund-experiment-lc8) have already started to experiment.

In most existing solutions, the resources transferred to the open source ecosystem are usually optional and uncoordinated. By introducing a dedicated tax, we can make this much more systematic and ensure that the open source ecosystem always receives revenue relative to the size of the software sector.

***

I found this thread through Konstantin's post. I had the chance to talk to him briefly about this topic at the OFA Symposium. Chad Whitacre also knows my views in general. However, when I see such a thorough conversation, I can't help but share my thoughts. We're getting a little off-topic, and I might be repeating my views, but I hope you don't mind. Greetings and happy holidays!

**Comment by chadwhitacre** [comment]
We discussed this issue on our steering call today. Building out a proper "individual membership" program is a lot of work. We would need to duplicate and revise the whole process of marketing and selling the Pledge, defining criteria and onboarding individuals, listing members, and presenting individual profiles. This duplicate structure would diffuse our message and create confusion. The primary goal of the Pledge is to unlock significant funding from corporations to maintainers. We need to focus on that, so I'm going to close this issue for now.

The two opportunities we have for individuals are:

1. **[Joining](https://opensourcepledge.com/join/) the Pledge** as a company-of-one.
2. **[Endorsing](https://opensourcepledge.com/endorsements/) the Pledge** as an individual. 

@mishushakov @vinogradovkonst et al. We would love to have your support in either of those ways. 🙏

P.S. @coni2k Your comment seems more relevant for #173. 😌
