### ISSUE TITLE
Document decision to turn off vulnerability reports

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#234]
I received this from Sentry's security team (they noticed because the `opensourcepledge` org is part of the `sentry` enterprise):

> Hey Chad, we noticed that Vlad turned off vulnerability reports for opensourcepledge/opensourcepledge.com. AFAIK it's not handling anything sensitive, but it stood out as an odd choice. Any chance you know the reasoning behind it?

Can you speak to this, @vladh?

**Comment by vladh** [comment]
Oh, yeah — we were getting Dependabot alerts, but they seemed to be false positives to me, because we're making a static website that doesn't take user input, so these warnings don't apply. So I turned it off to make the build process faster.

Sorry if this caused any alarm or confusion! 😨 

Happy to turn it back on!

**Comment by chadwhitacre** [comment]
Thanks for the explanation, Vlad. That suffices. :)
