### ISSUE TITLE
SaaS Pegasus joins the Open Source Pledge

### ISSUE THREAD

**Issue by czue** [opensourcepledge/opensourcepledge.com#291]
Hello! We (ok, I) would like to join the open source pledge on behalf of my single-person company, SaaS Pegasus.

**A link to your blog post.**

https://www.saaspegasus.com/about/open-source/ (2024)

**A short (less than 600 character) description of your company, including why you're joining.**

[SaaS Pegasus](https://www.saaspegasus.com/) is a starter project template that helps you create and deploy SaaS applications with Python and Django. While SaaS Pegasus is—at least for now—a closed-source, proprietary product, it is built on top of a vast open-source ecosystem. Adopting the open source pledge felt like a good way to give back to the developers whose work has made Pegasus possible.

**Your branding materials.**

_A glyph/icon in a square area with a non-transparent background:_

![rocket-laptop-square](https://github.com/user-attachments/assets/ebdc26ab-4b41-4a38-92ea-60f2eab86d8c)

_A glyph/icon in a square area with a transparent background._

![rocket-laptop-square-transparent](https://github.com/user-attachments/assets/5f2bde53-d6bf-4872-a410-a94a436d4aa4)

_A full name/wordmark in a wide rectangle with a transparent background._

.png:

![pegasus-wordmark-transparent](https://github.com/user-attachments/assets/7ec9d992-ff71-4ede-8c1f-f85126e44884)

.svg:

![wordmark-final](https://github.com/user-attachments/assets/f3b7a818-c2bf-4205-a030-46afb2bf3c5c)

**Comment by vladh** [comment]
It's great to have you @czue, and I think your willingness to give back to the Open Source ecosystem is amazing. 🥳 💃🏻 

Just one thing I noticed — would it be possible to get your logo as an SVG or other vector file? In general, vector files make it easier for us to feature you on the website and marketing materials. And specifically here, I noticed that your horizontal logo retains some white blooming around it.

**Comment by czue** [comment]
Thanks @vladh ! Excited to be giving backT

I just fixed the logo, but let me check if I can also get it as an svg.

**Comment by vladh** [comment]
Hmm, strictly speaking we have what we need, because we would use the icon for the member profile, and only the wordmark (text) for the homepage.

But I did notice that the SVG file has some issues because the logomark is an embedded base64 image. Here's how it renders in Inkscape:

![2024-12-17-15-13-17](https://github.com/user-attachments/assets/7f9d9ea6-3b42-44c1-9ba9-7e7127d63c57)

And Firefox when opened by itself (though it looks fine on GitHub?):

![2024-12-17-15-13-57](https://github.com/user-attachments/assets/6a7df288-3a9c-482d-b535-380cb5cf4762)

I'd look into getting a fully vector-based version, but this shouldn't block onboarding!

**Comment by czue** [comment]
Ok, weird. I'll take a look (probably tomorrow). Thanks for the quick response!

**Comment by czue** [comment]
Good to be here! FYI, @vladh I believe I have fixed the svg, but let me know if you're still seeing issues!

**Comment by vladh** [comment]
The new SVG is super useful, thank you! Onboarding now.

**Comment by vladh** [comment]
Done in #292. 🎉

**Comment by czue** [comment]
Awesome!
