### ISSUE TITLE
Recruit Members ahead of OOH launch

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#5]
We want to promote logos as part of #11. We need people committed by September 24 (week lead time for Sentry design, week lead time for Nasdaq).

Here's our [**CRM sheet** 🔒](https://docs.google.com/spreadsheets/d/1hzRN_ZJjlh4979HAp6wkhebXmlgXVX6i44tpQihJEdQ/edit).

**Comment by vladh** [comment]
It may be worth contacting [Collabora](https://www.collabora.com/), they mainly (but I don't think exclusively) develop OSS for clients and already have a policy that developers should dedicate some hours to contributing back to upstream projects. Interestingly, they're already a member of 1% for the Planet.

**Comment by chadwhitacre** [comment]
@vladh Can you reach out to them? If you want I'd be happy to have a call with you to go over what @selviano and I have been pitching people on so far, so we can be aligned. chadwhitacre@sentry.io if you want to set up a call. 🙏

**Comment by vladh** [comment]
@chadwhitacre On it! :)

**Comment by chadwhitacre** [comment]
Thanks! :-) 💃

**Comment by vladh** [comment]
@chadwhitacre Got a message back from Collabora, they said they're not interested in a cash pledge because they feel they already contribute to the FOSS ecosystem through non-cash means.

Happy to contact other potential pledgers if you have any lined up.

**Comment by chadwhitacre** [comment]
Thanks for reaching out and reporting back. Non-cash contributions are certainly valuable, though in our view not the whole of it. Let's keep brainstorming on good candidates.

**Comment by chadwhitacre** [comment]
Decision on call to have two sheets, public (limited details) and private (full details). Private is only available to the recruiting working group, led by @vladh. Ticket description updated accordingly.

**Comment by chadwhitacre** [comment]
Talking with @vladh on weekly steering call ... planning to focus this week on gathering names of candidate companies, keeping threads topped up that are already established, but waiting a week before sending new emails to new companies. Idea is let's see how far along we can be with build in a week, having real company profiles will prime the pumps on recruiting.

**Comment by chadwhitacre** [comment]
> We want to put logos on one of the billboards for https://github.com/opensourcepledge/osspledge.com/issues/11

Now aiming to work with Nasdaq for logos vs. using one of the SF billboards. Need to pin down Nasdaq still though.

**Comment by vladh** [comment]
I've triaged our [sponsors list](https://github.com/opensourcepledge/osp-tools/blob/main/gh_sponsor_finder/output/20240630-02.md) from the beginning up to “craftcms”, which brings us to a total of 65 new companies to contact listed in our [spreadsheet](https://docs.google.com/spreadsheets/d/1hzRN_ZJjlh4979HAp6wkhebXmlgXVX6i44tpQihJEdQ/edit?gid=0#gid=0).

The only remaining step before reaching out is to gather contact details for all these companies. I've asked the community on Discord for help with this because it's somewhat time-intensive.

**Comment by chadwhitacre** [comment]
First member from our [early adopter cohort](https://github.com/opensourcepledge/osspledge.com/issues/6#issuecomment-2269532574) in #41! 😱 😍 💃

**Comment by selviano** [comment]
Got written confirmation from Nasdaq that they will promote on the Times Sq Tower 💪

**Comment by chadwhitacre** [comment]
Woo-hoo! That's awesome! 🙌 Are they going to be able to rotate through multiple partner logos? Did you get into details like that?

**Comment by selviano** [comment]
it will be a static image, in a rotation of other static images throughout the day. They have an automated camera across the street which will capture our display and send it to us for social promotion/etc

**Comment by chadwhitacre** [comment]
(Moving this here from #6 ... )

Early adopters to test:

- [ ] Sentry
- [ ] Astral
- [x] HTTPToolkit
- [ ] Antithesis
- [ ] BrowserBase

**Comment by chadwhitacre** [comment]
We should reach out to people we've already talked to for intros to people on the list.

**Comment by chadwhitacre** [comment]
A public sheet with company name and status would be great for sharing in 1:1s to aid with network effect. @vladh Can we make the public sheet in an automated fashion from the private or would it have to manually kept in sync or ... ?

**Comment by vladh** [comment]
@chadwhitacre I'll figure out an automated solution!

**Comment by vladh** [comment]
@chadwhitacre Done!

Website: https://osp-members.vlad.website/

Code: https://github.com/opensourcepledge/osp-potential-member-list

This updates every 10 minutes from the spreadsheet.

Obviously we would ideally run it on a different domain, happy to configure that if you give me an A record or something.

**Comment by chadwhitacre** [comment]
Who! That's more than I expected! 😅

Do we want something so official to call out companies that have "refused"? Comes off maybe harsher than we want? Or maybe as harsh as we want? 🤔

**Comment by vladh** [comment]
Could do “declined” which feels a smidge softer, but I also don't feel too much of a need to launder it, readers can make up their own opinions on whether refusal is okay or not. 😛

**Comment by chadwhitacre** [comment]
This reminds me of the [Python 3 Wall of Shame](https://archive.is/qPJUm). The difference there is that we are having private conversations with companies on behalf of the Pledge and then publishing the results of those conversations publicly. Making it branded feels somehow different than putting it in a public Google Sheet. If it's branded and associated with the main driver of member recruiting (i.e., you @vladh ;) then it may as well be integrated into osspledge.com itself. We then have a business model quite like Docker's where sales contacts companies (I was part of this at Sentry) and are like "You're probably using Docker a lot, please check and then pay us." I'm not opposed to that necessarily but it feels like something we should talk through and commit to together.

**Comment by vladh** [comment]
I'm waiting for #45 to be closed before we send out the next batch of member recruiting emails.

Another thing that needs to be done, which I'll document here soon, is workshopping the email to be sent to members.

**Comment by chadwhitacre** [comment]
Sounds good. I dropped a line w/ David internally, will follow up on #45 if/when I hear back.

**Comment by vladh** [comment]
Recruitment email draft 🔒: https://docs.google.com/document/d/1btur1wMK2Dxi9RI7eXtF_OPDyvmqBZXfvsWSGCqiwKU/edit

Shared with @chadwhitacre, @Ethan-Arrowood, @selviano. Feedback welcome!

**Comment by chadwhitacre** [comment]
Next steps per call w/ @vladh @selviano:

- each target company gets an owner
- top up all directs
- go through google calendar history, update our CRM sheet
- collect list of friendlies
- circulate list of target companies w/ friendlies, ask is for a warm intro
- cold-email remaining
- set up round robin calls on cal.com
- set up a synchronization call w/ vlad michael chad

**Comment by chadwhitacre** [comment]
I did a little cleanup on the [CRM sheet](https://docs.google.com/spreadsheets/d/1hzRN_ZJjlh4979HAp6wkhebXmlgXVX6i44tpQihJEdQ/edit?gid=0#gid=0):

- first column company name now has the name linked, separate link column is gone
- owner column is a dropdown
- member status column is a dropdown
- I was gonna make "number of devs" a dropdown as well but I wanted to use [our buckets](https://github.com/opensourcepledge/osspledge.com/blob/736291ea2d8e9ea96f72335397c57ba64e12db3d/src/components/Leaderboard.astro#L21-L27) and it doesn't map cleanly so I gave up

**Comment by chadwhitacre** [comment]
I posted in the TODO Group Slack.

<img width="847" alt="image" src="https://github.com/user-attachments/assets/5653eff9-2743-47b4-b4c4-56d7a343e042">

**Comment by mkurz** [comment]
If you don't mind, I'd like to chime in on [the above conversation](https://github.com/opensourcepledge/osspledge.com/issues/5#issuecomment-2307850317) and share some thoughts: 

>>> Do we want something so official to call out companies that have "refused"? Comes off maybe harsher than we want? Or maybe as harsh as we want? 🤔

>> Could do “declined” which feels a smidge softer, but I also don't feel too much of a need to launder it, readers can make up their own opinions on whether refusal is okay or not. 😛

> This reminds me of the Python 3 Wall of Shame ... Making it branded feels somehow different than putting it in a public Google Sheet. If it's branded and associated with the main driver of member recruiting (i.e., you @vladh ;) then it may as well be integrated into osspledge.com itself. We then have a business model quite like Docker's where sales contacts companies (I was part of this at Sentry) and are like "You're probably using Docker a lot, please check and then pay us." I'm not opposed to that necessarily but it feels like something we should talk through and commit to together.

For completeness, I'm linking a similar discussion in another thread [here](https://github.com/opensourcepledge/osspledge.com/issues/11#issuecomment-2269477395) where you initially talked about publicly shaming companies for not taking part.

So, I am an OSS developer funded by the community, and I've personally been in a situation where I reached out to companies that heavily relied on the OSS project I maintain. These companies were essentially building their entire business on it, with 100+ employees and millions in revenue. The companies were still small enough that I could directly contact the CEO/CTO - this wasn't a case like Amazon, where bureaucracy would make it impossible to (directly) reach decision-makers.

I remember a case where I asked one of those companies for donations, like always, to help sustain the project. To make a long story short, I got ghosted. However, I know for a fact that their management team received my emails and even discussed it, as an employee there confirmed it was brought up in meetings.

I'm sharing this because, at the time, I was incredibly frustrated (yes, pissed off) that they didn't even bother to respond to my multiple requests (which spanned over more than half a year). From my perspective, it was like:

- They knew they were heavily reliant on the OSS project for their core business and were and still do make good money with it.
- But they still didn't want to financially support our OSS project.
- This, despite the fact that without enough funding, the OSS project was at risk of failing, which would have cost them far more in migration and rebuilding efforts than simply donating a few thousand dollars per year to keep it going.

Even though this behavior seemed completely irrational to me - and, frankly, still does - I came to realize a few things:

- You cannot force anyone to donate to an open-source project.
- The nature of open source is that it is open - no one is obligated to contribute.
- Forcing, blaming, or shaming companies or individuals doesn't foster positive relationships and rarely leads to good outcomes.

Instead, the point I want to make here is that rather than blaming or shaming companies for not participating in the OSS Pledge, we should take a more positive approach.

I believe this is about helping companies understand that supporting such a movement is ultimately in their own best interest. IMHO it should be presented something like this:  
"Funding OSS developers leads to more robust and innovative OSS software that companies can rely on to grow their business and increase profitability. Supporting OSS maintainers drives the innovations that benefit your company and the industry as a whole."

I'd even go so far as to compare OSS maintainers to the steam engine during the Industrial Revolution, or to broadband internet in the last 30 years. These might be bold comparisons, but I think you get the idea - OSS maintainers are a key part of the infrastructure of our modern world. I really like Collabora's “Open First” statement [on their front page](https://www.collabora.com/):  
_"Free and open access to software is the only way to cope with today's rate of innovation. None of the major technology innovations and infrastructure evolutions of the past 10 years would have been possible without Open Source."_

My concrete suggestion is that if you create a dedicated page or section on the site listing companies that are known to use open source software (and, to be fair, all companies do), you frame it positively. For example: _"Hey Nvidia! We see you love OSS as much as we do - why not jump on board and join our movement? We'd love to hear from you!"_

Even framed in a positive tone, people would likely still “read between the lines” and understand that these are companies that don't yet contribute back to the community. This could subtly apply social pressure for them to take part.

In the end, social pressure shouldn't even be necessary. At some point, the movement will be big enough that even large corporations won't be able to justify not being part of it. Even better would be if the mindset shift reaches decision-makers, so they finally realize that supporting OSS developers is actually beneficial to their business.

**Comment by vladh** [comment]
@mkurz I don't have much to add, but I just wanted to say (1) thank you for sharing the experience you've gone through regarding funding, and (2) I agree with your point that a positive tone is most productive, that it's still possible to call out companies even while having a positive tone, and that that's probably the best way to go.

**Comment by vladh** [comment]
TODO: clarify that 15 Sep is no longer the deadline for members to be featured in the OOH advertising campaign — new deadline is 24 Sep.

**Comment by chadwhitacre** [comment]
I'm calling this done, insofar as we now have 20 members onboarded with another one or two in the pipeline, and we just cut off access to the Nasdaq Tower. We'll still give an "Innovator" badge to anyone who joins before Oct 8 but the primary task of recruiting is behind us.
